version: '2'
services:
    salesapp-app:
        image: salesapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://salesapp-postgresql:5432/salesApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    salesapp-postgresql:
        extends:
            file: postgresql.yml
            service: salesapp-postgresql
